- name: Setup Device
  hosts: localhost
  tasks:
    - name: Create Directories
      file:
        path: "{{item}}"
        state: directory
      loop:
        - ~/bin
        - ~/tmp
    - import_tasks: ./tasks/setup_dotbot.yml
      vars:
        repo: git@github.com:DrDynamic/dotbot-home.git
#        repo: https://github.com/DrDynamic/dotbot-home.git
    - import_tasks: ./tasks/setup_zsh.yml
      vars:
        local_user: "{{ansible_user_id}}"
    - import_tasks: ./tasks/install_packages.yml
      vars:
        system_packages:
          - kitty 
          - zsh
          - flatpak
          - snapd
          - neovim
          - curl
          - git
          - bpytop
          - fonts-powerline
        flatpaks:
          - com.bitwarden.desktop
          - com.github.tchx84.Flatseal
          - com.jetbrains.PhpStorm
          - org.kde.krita
          - org.chromium.Chromium
          - com.ktechpit.whatsie
        snaps:
        snaps_classic:
          - code
          - phpstorm
    - import_tasks: ./tasks/setup_webdev.yml
    - import_tasks: ./tasks/setup_gamedev.yml
    - import_tasks: ./tasks/setup_godev.yml
#    - import_tasks: ./tasks/setup_kzv.yml