- name: Setup Device
  hosts: localhost
  tasks:
    - name: Create Directories
      file:
        path: "{{item}}"
        state: directory
      loop:
        - ~/bin
        - ~/tmp
    - import_tasks: ./tasks/setup_dotbot.yml
      vars:
        repo: git@github.com:DrDynamic/dotbot-home.git
#        repo: https://github.com/DrDynamic/dotbot-home.git
    - import_tasks: ./tasks/install_packages.yml
      vars:
        system_packages:
          - zsh
          - autojump
          - flatpak
          - snapd
          - neovim
          - curl
          - git
          - bpytop
          - fonts-powerline
        flatpaks:
          - com.bitwarden.desktop
          - com.github.tchx84.Flatseal
          - org.kde.krita
          - org.chromium.Chromium
          - com.ktechpit.whatsie
        snaps: []
        snaps_classic:
          - code
          - phpstorm
    - name: Install Ghostty
      shell:
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh)"
        creates: /bin/ghostty
      become: true
    - import_tasks: ./tasks/setup_zsh.yml
      vars:
        local_user: "{{ansible_user_id}}"
    - import_tasks: ./tasks/setup_webdev.yml
      vars:
        local_user: "{{ansible_user_id}}"
        laradock: "https://github.com/Laradock/laradock.git"
    - import_tasks: ./tasks/setup_gamedev.yml
    - import_tasks: ./tasks/setup_godev.yml
