- name: Setup Device
  hosts: localhost
  tasks:
    - name: "Configure Gnome Terminal"
      block:
      - name: "Get default profile"
        shell: gsettings get org.gnome.Terminal.ProfilesList default | awk -F \' '{print $2}'
        register: gnome_terminal_profile
      - name: "Debug DCONF"
        ansible.builtin.debug:
          msg: "dconf write /org/gnome/terminal/legacy/profiles:/:{{gnome_terminal_profile.stdout}}/key"
