- name: Install ZSH
  become: true
  package:
    name: zsh
    state: present

- name: Install Fonts
  block:
    - name: Copy Fonts
      copy:
        src: "{{item}}"
        dest: ~/.local/share/fonts/
      with_fileglob:
        - "./fonts/*"
    - name: Publish Fonts
      command: fc-cache -f -v

- name: Setup OhMyZsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --keep-zshrc --unattended"
    creates: "~/.oh-my-zsh/oh-my-zsh.sh"
- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    accept_hostkey: yes
- name: Install zsh powerlevel10k
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    accept_hostkey: true
- name: Set Zsh as shell
  user:
    name: "{{local_user}}"
    shell: /usr/bin/zsh
  become: true