- name: Create Directories
  file:
    path: "{{item}}"
    state: directory
  loop:
    - ~/Projects/vendor
    - ~/Projects/go
- name: Get filename prefix with latest version
  set_fact:
    filename_prefix: "{{ lookup('url', 'https://golang.org/VERSION?m=text', wantlist=True)[0] }}"
- name: Download and extract the archive {{ filename_prefix }}.linux-amd64.tar.gz
  unarchive:
    src: "https://dl.google.com/go/{{ filename_prefix }}.linux-amd64.tar.gz"
    dest: ~/Projects/vendor
    remote_src: yes
    creates: ~/Projects/vendor/go
