- name: Create Directories
  file:
    path: "{{item}}"
    state: directory
  loop:
    - ~/Projects/vendor
    - ~/Projects/go
- name: Get filename prefix with latest version
  set_fact:
    filename_prefix: "{{ lookup('url', https://golang.org/VERSION?m=text, split_lines=False) }}"

- name: Try to get current go version installed
  command: go version
  register: result
  changed_when: false
- name: Set current_version var to the current
  set_fact:
    current_version: "{{ result.stdout.split(' ')[2] }}"
  when: result.failed == false
- name: Set current_version var to none
  set_fact:
    current_version: "none"
  when: result.failed == true
- debug:
    var: current_version
- name: Download and extract the archive {{ filename_prefix }}.linux-amd64.tar.gz
  become: true
  unarchive:
      src: "https://dl.google.com/go/{{ filename_prefix }}.linux-amd64.tar.gz"
      dest: ~/Projects/vendor
      remote_src: yes
  when: current_version != filename_prefix