- name: Create direcory structure
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - ~/Projects/kzv/
    - ~/Projects/experiments
    - ~/Projects/own/
- name: Install docker dependencies
  become: true
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
- name: Add Docker apt repository key.
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
#- name: Add Docker GPG apt Key
#  become: true
#  apt_key:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    state: present
- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
- name: Update apt and install docker-ce
  become: true
  package:
    name: 
      - docker-ce
      - docker-compose-plugin
    state: latest
    update_cache: true
- name: "Add {{ local_user }} to docker group"
  become: true
  user:
    name: "{{ local_user }}"
    append: true
    groups: docker

